name: Pylint

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false   # nechci, aby nový push rušil rozběhnutý běh

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint

      - name: Run pylint
        run: |
          FILES="$(git ls-files '*.py')"
          if [ -z "$FILES" ]; then
            echo "No Python files found, skipping."
            exit 0
          fi
          pylint --fail-under=8.0 $FILES
          # pokud chceš, aby lint jen reportoval a neblokoval build:
          # pylint $FILES || true
